pipelines:
  - name: taskTest
    steps:
      # - name: trigger_1
      #   type: Bash
      #   execution:
      #     onExecute:
      #       - printenv
      #       - echo "done"
      - name: trigger_2
        type: Bash
        configuration:
          integrations:
            - name: artifactory
        #   chronological: true
          # inputSteps: 
        #     - name: trigger_1
        execution:
          onExecute:
            - task: jfrog/setup-jfrog-cli@v0.1.0
              input:
                version: "2.26.1"  
