# resources:
  # - name: gitRes
  #   type: GitRepo
  #   configuration:
  #     gitProvider: finalTest
  #     path: seekhJaunga/pipelineBasic
  #     buildOn:
  #        branchCreate: false
  #        commit: false
pipelines:
  - name: taskTest
    configuration:
      jfrogCliVersion: 2
    steps:
      # - name: trigger_1
      #   type: Bash
      #   execution:
      #     onExecute:
      #       - printenv
      #       - echo "done"
      - name: trigger_2
        type: Bash
        configuration:
          integrations:
            - name: punyaTest
        #   chronological: true
          # inputSteps: 
        #     - name: trigger_1
        execution:
          onExecute:
            - jfrog -v
            - jf -v
            - ls -latrh $(which jfrog)
            - ls -latrh $(which jf)
            - task: jfrog/setup-jfrog-cli@v0.1.0
              input:
                version: "2.26.1"
            - jfrog -v
